//this list only contains the leaves of the tree structure
//TODO: find array that includes the category titles "Air Conditioners & Heat Pumps" and integrate them into the tree structure
const whereDoesItGo = [
{label:"AC Unit",value:'HouseholdItems/Appliances/AirConditionersHeatPumps/index.htm',hasChild:false},
{label:"Heat Pumps",value:'HouseholdItems/Appliances/AirConditionersHeatPumps/index.htm',hasChild:false},
{label:"Heating Apparatus",value:'HouseholdItems/Appliances/AirConditionersHeatPumps/index.htm',hasChild:false},
{label:"Air Conditioning Units",value:'HouseholdItems/Appliances/AirConditionersHeatPumps/index.htm',hasChild:false},
{label:"Dish Washers",value:'HouseholdItems/Appliances/OtherLargeAppliances/index.htm',hasChild:false},
{label:"Dishwashers",value:'HouseholdItems/Appliances/OtherLargeAppliances/index.htm',hasChild:false},
{label:"Chest Freezer",value:'HouseholdItems/Appliances/RefrigeratorsFreezers/index.htm',hasChild:false},
{label:"Fridges",value:'HouseholdItems/Appliances/RefrigeratorsFreezers/index.htm',hasChild:false},
{label:"Freezers",value:'HouseholdItems/Appliances/RefrigeratorsFreezers/index.htm',hasChild:false},
{label:"Electric Stoves",value:'HouseholdItems/Appliances/Stoves/index.htm',hasChild:false},
{label:"Gas Stoves",value:'HouseholdItems/Appliances/Stoves/index.htm',hasChild:false},
{label:"Electric Ranges",value:'HouseholdItems/Appliances/Stoves/index.htm',hasChild:false},
{label:"Gas Ranges",value:'HouseholdItems/Appliances/Stoves/index.htm',hasChild:false},
{label:"Washing MacHines",value:'HouseholdItems/Appliances/WashersDryers/index.htm',hasChild:false},
{label:"Tumble Dryers",value:'HouseholdItems/Appliances/WashersDryers/index.htm',hasChild:false},
{label:"Electric Dryers",value:'HouseholdItems/Appliances/WashersDryers/index.htm',hasChild:false},
{label:"Gas Dryers",value:'HouseholdItems/Appliances/WashersDryers/index.htm',hasChild:false},
{label:"Dryers",value:'HouseholdItems/Appliances/WashersDryers/index.htm',hasChild:false},
{label:"Electric Water Heaters",value:'HouseholdItems/Appliances/WaterHeaters/index.htm',hasChild:false},
{label:"Gas Water Heaters",value:'HouseholdItems/Appliances/WaterHeaters/index.htm',hasChild:false},
{label:"Disposable Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"AA Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"Batteries - Household",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"AAA Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"D Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"C Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"9 Volt Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"12 Volt Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"9-Volt Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"12-Volt Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"Household Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"Single Use Batteries",value:'HouseholdItems/Batteries/AlkalineBatteries/index.htm',hasChild:false},
{label:"Button Batteries",value:'HouseholdItems/Batteries/CameraWatchBatteries/index.htm',hasChild:false},
{label:"Button Cell Batteries ",value:'HouseholdItems/Batteries/CameraWatchBatteries/index.htm',hasChild:false},
{label:"Watch Batteries",value:'HouseholdItems/Batteries/CameraWatchBatteries/index.htm',hasChild:false},
{label:"Laptop Batteries",value:'HouseholdItems/Batteries/ComputerBatteries/index.htm',hasChild:false},
{label:"Mobile Phone Batteries",value:'HouseholdItems/Batteries/CellPhoneBatteries/index.htm',hasChild:false},
{label:"Lithium Ion Batteries",value:'HouseholdItems/Batteries/LithiumBatteries/index.htm',hasChild:false},
{label:"Lithium-Metal Batteries",value:'HouseholdItems/Batteries/LithiumBatteries/index.htm',hasChild:false},
{label:"Lib",value:'HouseholdItems/Batteries/LithiumBatteries/index.htm',hasChild:false},
{label:"Li-Ion Batteries",value:'HouseholdItems/Batteries/LithiumBatteries/index.htm',hasChild:false},
{label:"Rechargeable Lithium Ion Battery",value:'HouseholdItems/Batteries/RechargeableBatteries/index.htm',hasChild:false},
{label:"Lead Batteries",value:'HouseholdItems/Batteries/CarLead-AcidBatteries/index.htm',hasChild:false},
{label:"Lead-Acid Batteries",value:'HouseholdItems/Batteries/CarLead-AcidBatteries/index.htm',hasChild:false},
{label:"Lead Acid Batteries",value:'HouseholdItems/Batteries/CarLead-AcidBatteries/index.htm',hasChild:false},
{label:"Adult Diapers",value:'HouseholdItems/BathroomLaundry/DisposableDiapers/index.htm',hasChild:false},
{label:"Baby Diapers",value:'HouseholdItems/BathroomLaundry/DisposableDiapers/index.htm',hasChild:false},
{label:"Diapers",value:'HouseholdItems/BathroomLaundry/DisposableDiapers/index.htm',hasChild:false},
{label:"Huggies",value:'HouseholdItems/BathroomLaundry/DisposableDiapers/index.htm',hasChild:false},
{label:"Nappies",value:'HouseholdItems/BathroomLaundry/DisposableDiapers/index.htm',hasChild:false},
{label:"Pull Ups",value:'HouseholdItems/BathroomLaundry/DisposableDiapers/index.htm',hasChild:false},
{label:"Baby Wipes",value:'HouseholdItems/BathroomLaundry/FlushableWipes/index.htm',hasChild:false},
{label:"Disposable Wipes",value:'HouseholdItems/BathroomLaundry/FlushableWipes/index.htm',hasChild:false},
{label:"Wipes",value:'HouseholdItems/BathroomLaundry/FlushableWipes/index.htm',hasChild:false},
{label:"Biodegradable Wipes",value:'HouseholdItems/BathroomLaundry/FlushableWipes/index.htm',hasChild:false},
{label:"Porcelain Toilets",value:'HouseholdItems/BathroomLaundry/PorcelainItems/index.htm',hasChild:false},
{label:"Bath Tubs",value:'HouseholdItems/BathroomLaundry/PorcelainItems/index.htm',hasChild:false},
{label:"Sinks - Porcelain",value:'HouseholdItems/BathroomLaundry/PorcelainItems/index.htm',hasChild:false},
{label:"Toilets - Porcelain",value:'HouseholdItems/BathroomLaundry/PorcelainItems/index.htm',hasChild:false},
{label:"Tubs - Porcelain",value:'HouseholdItems/BathroomLaundry/PorcelainItems/index.htm',hasChild:false},
{label:"Tubs - Metal",value:'HouseholdItems/BathroomLaundry/SinkTubsFixtures-Metal/index.htm',hasChild:false},
{label:"Sinks - Metal",value:'HouseholdItems/BathroomLaundry/SinkTubsFixtures-Metal/index.htm',hasChild:false},
{label:"Fixtures - Metal",value:'HouseholdItems/BathroomLaundry/SinkTubsFixtures-Metal/index.htm',hasChild:false},
{label:"Fitted Sheets",value:'HouseholdItems/Bedroom/BeddingLinens/index.htm',hasChild:false},
{label:"Duvet Cover",value:'HouseholdItems/Bedroom/BeddingLinens/index.htm',hasChild:false},
{label:"Linens",value:'HouseholdItems/Bedroom/BeddingLinens/index.htm',hasChild:false},
{label:"Pillow Cases",value:'HouseholdItems/Bedroom/BeddingLinens/index.htm',hasChild:false},
{label:"Sheets",value:'HouseholdItems/Bedroom/BeddingLinens/index.htm',hasChild:false},
{label:"Clothes Hangers - Plastic",value:'HouseholdItems/Bedroom/PlasticClothesHangers/index.htm',hasChild:false},
{label:"Clothes Hangers - Wire",value:'HouseholdItems/Bedroom/ClothesHangersWire/index.htm',hasChild:false},
{label:"Wire Hangers",value:'HouseholdItems/Bedroom/ClothesHangersWire/index.htm',hasChild:false},
{label:"Clothes Hangers - Wood",value:'HouseholdItems/Bedroom/ClothesHangersWood/index.htm',hasChild:false},
{label:"Sweaters",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Sweatshirts",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"T Shirts",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Clothing",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Jackets",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Shoes",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Pants",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Polo Shirts",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Shirts",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Used Clothing",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Coats",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"T-Shirts",value:'HouseholdItems/Bedroom/ClothesShoes/index.htm',hasChild:false},
{label:"Beds",value:'HouseholdItems/Bedroom/MatressesFutons/index.htm',hasChild:false},
{label:"Box Springs",value:'HouseholdItems/Bedroom/MatressesFutons/index.htm',hasChild:false},
{label:"Bunk Beds",value:'HouseholdItems/Bedroom/MatressesFutons/index.htm',hasChild:false},
{label:"Memory Foam",value:'HouseholdItems/Bedroom/MatressesFutons/index.htm',hasChild:false},
{label:"Futons",value:'HouseholdItems/Bedroom/MatressesFutons/index.htm',hasChild:false},
{label:"Bikes",value:'HouseholdItems/GarageOutdoor/BicyclesBikeParts/index.htm',hasChild:false},
{label:"Bike Chains",value:'HouseholdItems/GarageOutdoor/BicyclesBikeParts/index.htm',hasChild:false},
{label:"Bike Parts",value:'HouseholdItems/GarageOutdoor/BicyclesBikeParts/index.htm',hasChild:false},
{label:"Bike Tires",value:'HouseholdItems/GarageOutdoor/BicyclesBikeParts/index.htm',hasChild:false},
{label:"Bike Wheels",value:'HouseholdItems/GarageOutdoor/BicyclesBikeParts/index.htm',hasChild:false},
{label:"Handlebars",value:'HouseholdItems/GarageOutdoor/BicyclesBikeParts/index.htm',hasChild:false},
{label:"Booster Seats",value:'HouseholdItems/GarageOutdoor/ChildCarSeats/index.htm',hasChild:false},
{label:"Baby Seats",value:'HouseholdItems/GarageOutdoor/ChildCarSeats/index.htm',hasChild:false},
{label:"Car Seats",value:'HouseholdItems/GarageOutdoor/ChildCarSeats/index.htm',hasChild:false},
{label:"Child Booster Seats",value:'HouseholdItems/GarageOutdoor/ChildCarSeats/index.htm',hasChild:false},
{label:"Child Safety Seats ",value:'HouseholdItems/GarageOutdoor/ChildCarSeats/index.htm',hasChild:false},
{label:"Safety Seats",value:'HouseholdItems/GarageOutdoor/ChildCarSeats/index.htm',hasChild:false},
{label:"Rubber Hoses",value:'HouseholdItems/GarageOutdoor/GardenHoses/index.htm',hasChild:false},
{label:"Garden Hoses",value:'HouseholdItems/GarageOutdoor/GardenHoses/index.htm',hasChild:false},
{label:"Hoses",value:'HouseholdItems/GarageOutdoor/GardenHoses/index.htm',hasChild:false},
{label:"Gas Lawn Mowers",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Gas Mowers",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Mowers",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Hover Mowers",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Rotary Lawn Mowers",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Power Equipment",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Electric Mowers",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Electric Lawn Mowers",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Push Mowers",value:'HouseholdItems/GarageOutdoor/LawnMowersPowerEquipment/index.htm',hasChild:false},
{label:"Paint - Latex",value:'HouseholdItems/GarageOutdoor/Paint-Latex/index.htm',hasChild:false},
{label:"Paint - Oil Based",value:'HouseholdItems/GarageOutdoor/Oil-BasedPaint/index.htm',hasChild:false},
{label:"Paint - Oil-Based",value:'HouseholdItems/GarageOutdoor/Oil-BasedPaint/index.htm',hasChild:false},
{label:"Oil Paints",value:'HouseholdItems/GarageOutdoor/Oil-BasedPaint/index.htm',hasChild:false},
{label:"Shrubs",value:'HouseholdItems/GarageOutdoor/PlantTreeSalvage/index.htm',hasChild:false},
{label:"4 Inch Pots",value:'HouseholdItems/GarageOutdoor/PlantPots/index.htm',hasChild:false},
{label:"5 Gallon Plant Pot",value:'HouseholdItems/GarageOutdoor/PlantPots/index.htm',hasChild:false},
{label:"Nursery Pots",value:'HouseholdItems/GarageOutdoor/PlantPots/index.htm',hasChild:false},
{label:"Plant Containers",value:'HouseholdItems/GarageOutdoor/PlantPots/index.htm',hasChild:false},
{label:"Plastic Pots",value:'HouseholdItems/GarageOutdoor/PlantPots/index.htm',hasChild:false},
{label:"Kids Plastic Pool",value:'HouseholdItems/GarageOutdoor/PlasticOutdoorFurniture/index.htm',hasChild:false},
{label:"Kids Pool ",value:'HouseholdItems/GarageOutdoor/PlasticOutdoorFurniture/index.htm',hasChild:false},
{label:"Patio Furniture",value:'HouseholdItems/GarageOutdoor/PlasticOutdoorFurniture/index.htm',hasChild:false},
{label:"Chairs - Plastic",value:'HouseholdItems/GarageOutdoor/PlasticOutdoorFurniture/index.htm',hasChild:false},
{label:"Furniture - Plastic",value:'HouseholdItems/GarageOutdoor/PlasticOutdoorFurniture/index.htm',hasChild:false},
{label:"Laundry Baskets - Plastic",value:'HouseholdItems/GarageOutdoor/PlasticOutdoorFurniture/index.htm',hasChild:false},
{label:"Totes - Plastic",value:'HouseholdItems/GarageOutdoor/PlasticOutdoorFurniture/index.htm',hasChild:false},
{label:"Rigid Plastics",value:'HouseholdItems/GarageOutdoor/PlasticOutdoorFurniture/index.htm',hasChild:false},
{label:"Balls",value:'HouseholdItems/GarageOutdoor/ToysSportingGoods/index.htm',hasChild:false},
{label:"Bats",value:'HouseholdItems/GarageOutdoor/ToysSportingGoods/index.htm',hasChild:false},
{label:"Nets",value:'HouseholdItems/GarageOutdoor/ToysSportingGoods/index.htm',hasChild:false},
{label:"Sporting Goods",value:'HouseholdItems/GarageOutdoor/ToysSportingGoods/index.htm',hasChild:false},
{label:"Rackets",value:'HouseholdItems/GarageOutdoor/ToysSportingGoods/index.htm',hasChild:false},
{label:"Paddles",value:'HouseholdItems/GarageOutdoor/ToysSportingGoods/index.htm',hasChild:false},
{label:"Sports Equipment",value:'HouseholdItems/GarageOutdoor/ToysSportingGoods/index.htm',hasChild:false},
{label:"Cookie Sheets",value:'HouseholdItems/Kitchen/BakingTraysCookieSheets/index.htm',hasChild:false},
{label:"Baking Sheets",value:'HouseholdItems/Kitchen/BakingTraysCookieSheets/index.htm',hasChild:false},
{label:"Cookie Trays",value:'HouseholdItems/Kitchen/BakingTraysCookieSheets/index.htm',hasChild:false},
{label:"Trays",value:'HouseholdItems/Kitchen/BakingTraysCookieSheets/index.htm',hasChild:false},
{label:"Cake Pans",value:'HouseholdItems/Kitchen/BakingTraysCookieSheets/index.htm',hasChild:false},
{label:"Cake Tins",value:'HouseholdItems/Kitchen/BakingTraysCookieSheets/index.htm',hasChild:false},
{label:"Tins",value:'HouseholdItems/Kitchen/CookieTins/index.htm',hasChild:false},
{label:"Cookie Containers",value:'HouseholdItems/Kitchen/CookieTins/index.htm',hasChild:false},
{label:"Bowls",value:'HouseholdItems/Kitchen/MugsPlatesBowls/index.htm',hasChild:false},
{label:"Coffee Mugs",value:'HouseholdItems/Kitchen/MugsPlatesBowls/index.htm',hasChild:false},
{label:"Dinner Plates",value:'HouseholdItems/Kitchen/MugsPlatesBowls/index.htm',hasChild:false},
{label:"Plates",value:'HouseholdItems/Kitchen/MugsPlatesBowls/index.htm',hasChild:false},
{label:"Cloth Bags",value:'HouseholdItems/Kitchen/ReusableShoppingBags/index.htm',hasChild:false},
{label:"Bags - Cloth",value:'HouseholdItems/Kitchen/ReusableShoppingBags/index.htm',hasChild:false},
{label:"Shopping Bags - Cloth",value:'HouseholdItems/Kitchen/ReusableShoppingBags/index.htm',hasChild:false},
{label:"Cloth Shopping Bags",value:'HouseholdItems/Kitchen/ReusableShoppingBags/index.htm',hasChild:false},
{label:"Christmas Lights",value:'HouseholdItems/LightsBulbs/HolidayLights/index.htm',hasChild:false},
{label:"Holiday Lights ",value:'HouseholdItems/LightsBulbs/HolidayLights/index.htm',hasChild:false},
{label:"Party Lights",value:'HouseholdItems/LightsBulbs/HolidayLights/index.htm',hasChild:false},
{label:"Xmas Lights",value:'HouseholdItems/LightsBulbs/HolidayLights/index.htm',hasChild:false},
{label:"Light Bulbs - Fluorescent",value:'HouseholdItems/LightsBulbs/LightBulbsFluorescent/index.htm',hasChild:false},
{label:"Ceiling Lights",value:'HouseholdItems/LightsBulbs/LightBulbsFluorescent/index.htm',hasChild:false},
{label:"Fluorescent Tubes",value:'HouseholdItems/LightsBulbs/LightBulbsFluorescent/index.htm',hasChild:false},
{label:"Electric Bulbs - Fluorescent",value:'HouseholdItems/LightsBulbs/LightBulbsFluorescent/index.htm',hasChild:false},
{label:"Electric Tubes - Fluorescent",value:'HouseholdItems/LightsBulbs/LightBulbsFluorescent/index.htm',hasChild:false},
{label:"Light Bulbs - Halogen ",value:'HouseholdItems/LightsBulbs/LightBulbsHalogenXenon/index.htm',hasChild:false},
{label:"Light Bulbs - Xenon",value:'HouseholdItems/LightsBulbs/LightBulbsHalogenXenon/index.htm',hasChild:false},
{label:"Xenon Light Bulbs",value:'HouseholdItems/LightsBulbs/LightBulbsHalogenXenon/index.htm',hasChild:false},
{label:"Halogen Light Bulbs",value:'HouseholdItems/LightsBulbs/LightBulbsHalogenXenon/index.htm',hasChild:false},
{label:"Light Bulbs - Incandescent ",value:'HouseholdItems/LightsBulbs/LightBulbsIncandescent/index.htm',hasChild:false},
{label:"Light Bulbs - LED ",value:'HouseholdItems/LightsBulbs/LightBulbsLED/index.htm',hasChild:false},
{label:"Ashes",value:'HouseholdItems/MiscHousehold/Ashes/index.htm',hasChild:false},
{label:"Charcoal",value:'HouseholdItems/MiscHousehold/Ashes/index.htm',hasChild:false},
{label:"Burned Charcoal",value:'HouseholdItems/MiscHousehold/Ashes/index.htm',hasChild:false},
{label:"Briquette Ashes",value:'HouseholdItems/MiscHousehold/Ashes/index.htm',hasChild:false},
{label:"Fireplace Ashes",value:'HouseholdItems/MiscHousehold/Ashes/index.htm',hasChild:false},
{label:"Padding",value:'HouseholdItems/MiscHousehold/CarpetPadding/index.htm',hasChild:false},
{label:"Rugs",value:'HouseholdItems/MiscHousehold/CarpetPadding/index.htm',hasChild:false},
{label:"Cold Packs",value:'HouseholdItems/MiscHousehold/GelPacks/index.htm',hasChild:false},
{label:"Hot Packs",value:'HouseholdItems/MiscHousehold/GelPacks/index.htm',hasChild:false},
{label:"Ice Packs",value:'HouseholdItems/MiscHousehold/GelPacks/index.htm',hasChild:false},
{label:"Chairs",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Coffee Tables",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Couches",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Dining Room Tables",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Furniture",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Lazy Boy",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Love Seats",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Ottomans",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Recliners",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Sectional Couches",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Side Table",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Shoe Racks",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Sofas",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Tables",value:'HouseholdItems/MiscHousehold/HouseholdFurniture/index.htm',hasChild:false},
{label:"Filing Cabinets",value:'HouseholdItems/MiscHousehold/OfficeFurnitureEquipment/index.htm',hasChild:false},
{label:"Office Equipment",value:'HouseholdItems/MiscHousehold/OfficeFurnitureEquipment/index.htm',hasChild:false},
{label:"Office Chairs",value:'HouseholdItems/MiscHousehold/OfficeFurnitureEquipment/index.htm',hasChild:false},
{label:"Rolling Chairs",value:'HouseholdItems/MiscHousehold/OfficeFurnitureEquipment/index.htm',hasChild:false},
{label:"Desks",value:'HouseholdItems/MiscHousehold/OfficeFurnitureEquipment/index.htm',hasChild:false},
{label:"Shelf",value:'HouseholdItems/MiscHousehold/OfficeFurnitureEquipment/index.htm',hasChild:false},
{label:"Shelves",value:'HouseholdItems/MiscHousehold/OfficeFurnitureEquipment/index.htm',hasChild:false},
{label:"Dog Food",value:'HouseholdItems/MiscHousehold/PetFood/index.htm',hasChild:false},
{label:"Canned Cat Food",value:'HouseholdItems/MiscHousehold/PetFood/index.htm',hasChild:false},
{label:"Canned Dog Food",value:'HouseholdItems/MiscHousehold/PetFood/index.htm',hasChild:false},
{label:"Wet Cat Food",value:'HouseholdItems/MiscHousehold/PetFood/index.htm',hasChild:false},
{label:"Cat Litter",value:'HouseholdItems/MiscHousehold/PetWasteLitter/index.htm',hasChild:false},
{label:"Cat Poop",value:'HouseholdItems/MiscHousehold/PetWasteLitter/index.htm',hasChild:false},
{label:"Cat Waste",value:'HouseholdItems/MiscHousehold/PetWasteLitter/index.htm',hasChild:false},
{label:"Dog Poop",value:'HouseholdItems/MiscHousehold/PetWasteLitter/index.htm',hasChild:false},
{label:"Dog Waste",value:'HouseholdItems/MiscHousehold/PetWasteLitter/index.htm',hasChild:false},
{label:"Kitty Litter",value:'HouseholdItems/MiscHousehold/PetWasteLitter/index.htm',hasChild:false},
{label:"Poop",value:'HouseholdItems/MiscHousehold/PetWasteLitter/index.htm',hasChild:false},
{label:"Printer Ink",value:'HouseholdItems/MiscHousehold/PrinterCartridgesToner/index.htm',hasChild:false},
{label:"Epson Printer Ink",value:'HouseholdItems/MiscHousehold/PrinterCartridgesToner/index.htm',hasChild:false},
{label:"HP Printer Ink",value:'HouseholdItems/MiscHousehold/PrinterCartridgesToner/index.htm',hasChild:false},
{label:"Brother Printer Ink",value:'HouseholdItems/MiscHousehold/PrinterCartridgesToner/index.htm',hasChild:false},
{label:"Dell Printer Ink",value:'HouseholdItems/MiscHousehold/PrinterCartridgesToner/index.htm',hasChild:false},
{label:"Toner Cartridges",value:'HouseholdItems/MiscHousehold/PrinterCartridgesToner/index.htm',hasChild:false},
{label:"Fire Alarms",value:'HouseholdItems/MiscHousehold/SmokeDetectors/index.htm',hasChild:false},
{label:"Smoke Alarms",value:'HouseholdItems/MiscHousehold/SmokeDetectors/index.htm',hasChild:false},
{label:"Telephones - Landline",value:'HouseholdItems/MiscHousehold/TelephonesLandline/index.htm',hasChild:false},
{label:"Handsets",value:'HouseholdItems/MiscHousehold/TelephonesLandline/index.htm',hasChild:false},
{label:"Blinds",value:'HouseholdItems/MiscHousehold/WindowBlinds/index.htm',hasChild:false},
{label:"Shades",value:'HouseholdItems/MiscHousehold/WindowBlinds/index.htm',hasChild:false},
{label:"Window Shades",value:'HouseholdItems/MiscHousehold/WindowBlinds/index.htm',hasChild:false},
{label:"Photo Glass",value:'HouseholdItems/MiscHousehold/WindownPictureGlass/index.htm',hasChild:false},
{label:"Picture Frame Glass",value:'HouseholdItems/MiscHousehold/WindownPictureGlass/index.htm',hasChild:false},
{label:"Plate Glass",value:'HouseholdItems/MiscHousehold/WindownPictureGlass/index.htm',hasChild:false},
{label:"Construction Debris",value:'ConstructionDemolition/Exterior/MixedCD/index.htm',hasChild:false},
{label:"Construction Garbage",value:'ConstructionDemolition/Exterior/MixedCD/index.htm',hasChild:false},
{label:"Construction Waste",value:'ConstructionDemolition/Exterior/MixedCD/index.htm',hasChild:false},
{label:"Construction and Demolition Waste",value:'ConstructionDemolition/Exterior/MixedCD/index.htm',hasChild:false},
{label:"Mixed Construction Waste",value:'ConstructionDemolition/Exterior/MixedCD/index.htm',hasChild:false},
{label:"Ceiling Materials",value:'ConstructionDemolition/FloorsCeiling/AcousticCeilingTile/index.htm',hasChild:false},
{label:"Ceiling Panels",value:'ConstructionDemolition/FloorsCeiling/AcousticCeilingTile/index.htm',hasChild:false},
{label:"Ceiling Squares",value:'ConstructionDemolition/FloorsCeiling/AcousticCeilingTile/index.htm',hasChild:false},
{label:"Ceiling Tiles",value:'ConstructionDemolition/FloorsCeiling/AcousticCeilingTile/index.htm',hasChild:false},
{label:"Soundproofing",value:'ConstructionDemolition/FloorsCeiling/AcousticCeilingTile/index.htm',hasChild:false},
{label:"Asphalt Shingles",value:'ConstructionDemolition/FloorsCeiling/AsphaltRoofing/index.htm',hasChild:false},
{label:"Roofing Materials",value:'ConstructionDemolition/FloorsCeiling/AsphaltRoofing/index.htm',hasChild:false},
{label:"Shingles",value:'ConstructionDemolition/FloorsCeiling/AsphaltRoofing/index.htm',hasChild:false},
{label:"Tab Shingle",value:'ConstructionDemolition/FloorsCeiling/AsphaltRoofing/index.htm',hasChild:false},
{label:"Tear Off Asphalt Shingles",value:'ConstructionDemolition/FloorsCeiling/AsphaltRoofing/index.htm',hasChild:false},
{label:"Air Duct",value:'ConstructionDemolition/FurnacesFixtures/Ducts/index.htm',hasChild:false},
{label:"Duct Work",value:'ConstructionDemolition/FurnacesFixtures/Ducts/index.htm',hasChild:false},
{label:"Heating Duct",value:'ConstructionDemolition/FurnacesFixtures/Ducts/index.htm',hasChild:false},
{label:"Fiber Glass",value:'ConstructionDemolition/FurnacesFixtures/Fiberglass/index.htm',hasChild:false},
{label:"Filigree Glass",value:'ConstructionDemolition/FurnacesFixtures/Fiberglass/index.htm',hasChild:false},
{label:"Glass Thread",value:'ConstructionDemolition/FurnacesFixtures/Fiberglass/index.htm',hasChild:false},
{label:"Furnace Parts",value:'ConstructionDemolition/FurnacesFixtures/Furnaces/index.htm',hasChild:false},
{label:"Salvagable Materials",value:'ConstructionDemolition/SalvagedMaterials/index.htm',hasChild:false},
{label:"Asphalt Chunks ",value:'ConstructionDemolition/SoilRockBrickConcrete/ConcreteAsphalt/index.htm',hasChild:false},
{label:"Torn Up Asphalt",value:'ConstructionDemolition/SoilRockBrickConcrete/ConcreteAsphalt/index.htm',hasChild:false},
{label:"Pavement",value:'ConstructionDemolition/SoilRockBrickConcrete/ConcreteAsphalt/index.htm',hasChild:false},
{label:"Cement",value:'ConstructionDemolition/SoilRockBrickConcrete/ConcreteAsphalt/index.htm',hasChild:false},
{label:"Torn Up Concrete",value:'ConstructionDemolition/SoilRockBrickConcrete/ConcreteAsphalt/index.htm',hasChild:false},
{label:"Planting Soil",value:'ConstructionDemolition/SoilRockBrickConcrete/DirtSoil/index.htm',hasChild:false},
{label:"Potting Soil",value:'ConstructionDemolition/SoilRockBrickConcrete/DirtSoil/index.htm',hasChild:false},
{label:"Soil",value:'ConstructionDemolition/SoilRockBrickConcrete/DirtSoil/index.htm',hasChild:false},
{label:"Garden Soil",value:'ConstructionDemolition/SoilRockBrickConcrete/DirtSoil/index.htm',hasChild:false},
{label:"Dirt - Contaminated",value:'ConstructionDemolition/SoilRockBrickConcrete/ContaminatedSoil/index.htm',hasChild:false},
{label:"Soil - Contaminated",value:'ConstructionDemolition/SoilRockBrickConcrete/ContaminatedSoil/index.htm',hasChild:false},
{label:"Contaminated Soil",value:'ConstructionDemolition/SoilRockBrickConcrete/ContaminatedSoil/index.htm',hasChild:false},
{label:"Crushed Gravel",value:'ConstructionDemolition/SoilRockBrickConcrete/RockGravel/index.htm',hasChild:false},
{label:"Gravel",value:'ConstructionDemolition/SoilRockBrickConcrete/RockGravel/index.htm',hasChild:false},
{label:"Pea Gravel",value:'ConstructionDemolition/SoilRockBrickConcrete/RockGravel/index.htm',hasChild:false},
{label:"Torn Out Walling",value:'ConstructionDemolition/WindowsWalls/Drywall/index.htm',hasChild:false},
{label:"Wall Boards",value:'ConstructionDemolition/WindowsWalls/Drywall/index.htm',hasChild:false},
{label:"Wall Debris",value:'ConstructionDemolition/WindowsWalls/Drywall/index.htm',hasChild:false},
{label:"Broken Bottles",value:'ConstructionDemolition/WindowsWalls/BrokenGlass/index.htm',hasChild:false},
{label:"Broken Glasses",value:'ConstructionDemolition/WindowsWalls/BrokenGlass/index.htm',hasChild:false},
{label:"Broken Jars",value:'ConstructionDemolition/WindowsWalls/BrokenGlass/index.htm',hasChild:false},
{label:"Glass - Broken",value:'ConstructionDemolition/WindowsWalls/BrokenGlass/index.htm',hasChild:false},
{label:"Pieces of Broken Glass",value:'ConstructionDemolition/WindowsWalls/BrokenGlass/index.htm',hasChild:false},
{label:"Boards",value:'ConstructionDemolition/WoodWastes/LumberBoards/index.htm',hasChild:false},
{label:"Dimensional Lumber",value:'ConstructionDemolition/WoodWastes/LumberBoards/index.htm',hasChild:false},
{label:"Cut Lumber",value:'ConstructionDemolition/WoodWastes/LumberBoards/index.htm',hasChild:false},
{label:"Lumber Ends",value:'ConstructionDemolition/WoodWastes/LumberBoards/index.htm',hasChild:false},
{label:"Two by Fours",value:'ConstructionDemolition/WoodWastes/LumberBoards/index.htm',hasChild:false},
{label:"2 X 4s",value:'ConstructionDemolition/WoodWastes/LumberBoards/index.htm',hasChild:false},
{label:"Paneling",value:'ConstructionDemolition/WoodWastes/PanelingCompositeWoods/index.htm',hasChild:false},
{label:"Particle Board",value:'ConstructionDemolition/WoodWastes/PanelingCompositeWoods/index.htm',hasChild:false},
{label:"Wood Paneling",value:'ConstructionDemolition/WoodWastes/PanelingCompositeWoods/index.htm',hasChild:false},
{label:"Wood Panels",value:'ConstructionDemolition/WoodWastes/PanelingCompositeWoods/index.htm',hasChild:false},
{label:"Twigs",value:'ConstructionDemolition/WoodWastes/TreesBrush/index.htm',hasChild:false},
{label:"Sticks",value:'ConstructionDemolition/WoodWastes/TreesBrush/index.htm',hasChild:false},
{label:"Branches",value:'ConstructionDemolition/WoodWastes/TreesBrush/index.htm',hasChild:false},
{label:"Brush",value:'ConstructionDemolition/WoodWastes/TreesBrush/index.htm',hasChild:false},
{label:"Bushes",value:'ConstructionDemolition/WoodWastes/TreesBrush/index.htm',hasChild:false},
{label:"Logs",value:'ConstructionDemolition/WoodWastes/TreesBrush/index.htm',hasChild:false},
{label:"Tree Clippings",value:'ConstructionDemolition/WoodWastes/TreesBrush/index.htm',hasChild:false},
{label:"Tree Branches",value:'ConstructionDemolition/WoodWastes/TreesBrush/index.htm',hasChild:false},
{label:"Wood Waste - Clean",value:'ConstructionDemolition/WoodWastes/WoodWasteClean/index.htm',hasChild:false},
{label:"Wood - Clean",value:'ConstructionDemolition/WoodWastes/WoodWasteClean/index.htm',hasChild:false},
{label:"Scrap Wood",value:'ConstructionDemolition/WoodWastes/WoodWasteClean/index.htm',hasChild:false},
{label:"Wood Waste",value:'ConstructionDemolition/WoodWastes/WoodWasteClean/index.htm',hasChild:false},
{label:"Painted Boards",value:'ConstructionDemolition/WoodWastes/WoodWastePaintedTreated/index.htm',hasChild:false},
{label:"Treated Boards",value:'ConstructionDemolition/WoodWastes/WoodWastePaintedTreated/index.htm',hasChild:false},
{label:"Sealed Wood",value:'ConstructionDemolition/WoodWastes/WoodWastePaintedTreated/index.htm',hasChild:false},
{label:"Varnished Wood",value:'ConstructionDemolition/WoodWastes/WoodWastePaintedTreated/index.htm',hasChild:false},
{label:"Treated Lumber",value:'ConstructionDemolition/WoodWastes/WoodWastePaintedTreated/index.htm',hasChild:false},
{label:"Painted Wood",value:'ConstructionDemolition/WoodWastes/WoodWastePaintedTreated/index.htm',hasChild:false},
{label:"Boards With Nails",value:'ConstructionDemolition/WoodWastes/WoodWastePaintedTreated/index.htm',hasChild:false},
{label:"Treated Wood",value:'ConstructionDemolition/WoodWastes/WoodWastePaintedTreated/index.htm',hasChild:false},
{label:"DVDs",value:'Electronics/CDsDVDsFloppies/index.htm',hasChild:false},
{label:"Compact Discs",value:'Electronics/CDsDVDsFloppies/index.htm',hasChild:false},
{label:"Floppies",value:'Electronics/CDsDVDsFloppies/index.htm',hasChild:false},
{label:"Floppy Disks",value:'Electronics/CDsDVDsFloppies/index.htm',hasChild:false},
{label:"Hard Disks",value:'Electronics/CDsDVDsFloppies/index.htm',hasChild:false},
{label:"Smart Phones",value:'Electronics/CellPhones/index.htm',hasChild:false},
{label:"Alarm Clocks",value:'Electronics/ClockRadios/index.htm',hasChild:false},
{label:"Tablet Computer",value:'Electronics/ComputersLaptops/index.htm',hasChild:false},
{label:"Laptops",value:'Electronics/ComputersLaptops/index.htm',hasChild:false},
{label:"iPads",value:'Electronics/ComputersLaptops/index.htm',hasChild:false},
{label:"Tablets",value:'Electronics/ComputersLaptops/index.htm',hasChild:false},
{label:"Monitors",value:'Electronics/ComputerMonitors/index.htm',hasChild:false},
{label:"Computer Screens",value:'Electronics/ComputerMonitors/index.htm',hasChild:false},
{label:"Used Computer Monitors",value:'Electronics/ComputerMonitors/index.htm',hasChild:false},
{label:"Fax Machines",value:'Electronics/CopiersFaxMachines/index.htm',hasChild:false},
{label:"Copy Machines",value:'Electronics/CopiersFaxMachines/index.htm',hasChild:false},
{label:"Xerox Machines",value:'Electronics/CopiersFaxMachines/index.htm',hasChild:false},
{label:"Kindles",value:'Electronics/E-readers/index.htm',hasChild:false},
{label:"CD Players",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"DVD Players",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"CPUs",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"Electronic Waste",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"iPhones",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"Mobile Phones",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"Old Computers",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"Old PCs",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"PCs",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"Record Player",value:'Electronics/E-waste/index.htm',hasChild:false},
{label:"Sound Systems",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"Boom Boxes",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"Radio Receivers",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"Radio Tuners",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"Radios",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"Speakers",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"Stereos",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"Tape Decks",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"Tape Players",value:'Electronics/StereoAudioEquipment/index.htm',hasChild:false},
{label:"T.V.",value:'Electronics/Televisions/index.htm',hasChild:false},
{label:"TVs",value:'Electronics/Televisions/index.htm',hasChild:false},
{label:"Video Players",value:'Electronics/VCRs/index.htm',hasChild:false},
{label:"Cloth",value:'Fabric/FabricTextiles/index.htm',hasChild:false},
{label:"Curtains",value:'Fabric/FabricTextiles/index.htm',hasChild:false},
{label:"Textiles",value:'Fabric/FabricTextiles/index.htm',hasChild:false},
{label:"Used Cooking Oil",value:'Food/CookingOil/index.htm',hasChild:false},
{label:"Vegetable Oil",value:'Food/CookingOil/index.htm',hasChild:false},
{label:"Bacon Grease",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Coconut Oil",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Crisco",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"F.O.G.",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Fats",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Fog",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Greases",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Oils",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Olive Oil",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Peanut Oil",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Used Peanut Oil",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Used Sunflower Oil",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Used Vegetable Oil",value:'Food/FatsOilsGrease/index.htm',hasChild:false},
{label:"Leftovers",value:'Food/FoodScraps--All/index.htm',hasChild:false},
{label:"Scraps",value:'Food/FoodScraps--All/index.htm',hasChild:false},
{label:"Table Scraps",value:'Food/FoodScraps--All/index.htm',hasChild:false},
{label:"Leftover Food",value:'Food/FoodScraps--All/index.htm',hasChild:false},
{label:"Food Waste",value:'Food/FoodScraps--All/index.htm',hasChild:false},
{label:"Multivitamins",value:'Food/Vitamins/index.htm',hasChild:false},
{label:"Supplements",value:'Food/Vitamins/index.htm',hasChild:false},
{label:"Aluminum Sheets",value:'FoodPackaging/AluminumFoilTrays/index.htm',hasChild:false},
{label:"Aluminum Trays",value:'FoodPackaging/AluminumFoilTrays/index.htm',hasChild:false},
{label:"Foil",value:'FoodPackaging/AluminumFoilTrays/index.htm',hasChild:false},
{label:"Tin Foil",value:'FoodPackaging/AluminumFoilTrays/index.htm',hasChild:false},
{label:"Biodegradable Bags",value:'FoodPackaging/BagsPouches/CompostableBags/index.htm',hasChild:false},
{label:"Potato Chip Bags",value:'Plastic/Bags/ChipBags/index.htm',hasChild:false},
{label:"Tortilla Chip Bags",value:'Plastic/Bags/ChipBags/index.htm',hasChild:false},
{label:"Box Liners",value:'FoodPackaging/BagsPouches/FoodBoxLiners/index.htm',hasChild:false},
{label:"Food Box Bags",value:'FoodPackaging/BagsPouches/FoodBoxLiners/index.htm',hasChild:false},
{label:"Plastic Bags",value:'FoodPackaging/BagsPouches/GroceryBags/index.htm',hasChild:false},
{label:"Plastic Grocery Bags",value:'FoodPackaging/BagsPouches/GroceryBags/index.htm',hasChild:false},
{label:"To Go Bags",value:'FoodPackaging/BagsPouches/GroceryBags/index.htm',hasChild:false},
{label:"Popcorn Bags",value:'FoodPackaging/BagsPouches/MicrowavePopcornBags/index.htm',hasChild:false},
{label:"Plastics",value:'FoodPackaging/BagsPouches/PlasticNoRecycleSymbol/index.htm',hasChild:false},
{label:"Cat Food Bags",value:'FoodPackaging/BagsPouches/PetFoodBags/index.htm',hasChild:false},
{label:"Dog Food Bags",value:'FoodPackaging/BagsPouches/PetFoodBags/index.htm',hasChild:false},
{label:"Kibble Bags",value:'FoodPackaging/BagsPouches/PetFoodBags/index.htm',hasChild:false},
{label:"Animal Food Bags",value:'FoodPackaging/BagsPouches/PetFoodBags/index.htm',hasChild:false},
{label:"Plastic Produce Bags",value:'FoodPackaging/BagsPouches/ProduceBulkFoodBags/index.htm',hasChild:false},
{label:"Plastic Food Bags",value:'FoodPackaging/BagsPouches/ProduceBulkFoodBags/index.htm',hasChild:false},
{label:"Vegetable Bags",value:'FoodPackaging/BagsPouches/ProduceBulkFoodBags/index.htm',hasChild:false},
{label:"Produce Bags",value:'FoodPackaging/BagsPouches/ProduceBulkFoodBags/index.htm',hasChild:false},
{label:"Veggie Bags",value:'FoodPackaging/BagsPouches/ProduceBulkFoodBags/index.htm',hasChild:false},
{label:"Grocery Bags - Produce",value:'FoodPackaging/BagsPouches/ProduceBulkFoodBags/index.htm',hasChild:false},
{label:"Bulk Food Bags",value:'FoodPackaging/BagsPouches/ProduceBulkFoodBags/index.htm',hasChild:false},
{label:"Food Bags",value:'FoodPackaging/BagsPouches/ZiplocBags/index.htm',hasChild:false},
{label:"Food Storage Bags",value:'FoodPackaging/BagsPouches/ZiplocBags/index.htm',hasChild:false},
{label:"Freezer Storage Bags",value:'FoodPackaging/BagsPouches/ZiplocBags/index.htm',hasChild:false},
{label:"Freezer Bags",value:'FoodPackaging/BagsPouches/ZiplocBags/index.htm',hasChild:false},
{label:"Caps",value:'FoodPackaging/BottlesJugs/BottleCapsJarLids/index.htm',hasChild:false},
{label:"Lids",value:'FoodPackaging/BottlesJugs/BottleCapsJarLids/index.htm',hasChild:false},
{label:"1 Gallon Jugs",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"Bottles - Plastic",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"Jugs",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"Pop Bottles",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"Screw Top Bottles",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"Soda Bottles",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"Water Bottles",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"Plastic Bottles",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"One-Gallon Jugs",value:'FoodPackaging/BottlesJugs/PlasticBottlesWaterSoda/index.htm',hasChild:false},
{label:"Milk Jugs",value:'FoodPackaging/BottlesJugs/PlasticMilkJuiceJug/index.htm',hasChild:false},
{label:"Juice Jugs",value:'FoodPackaging/BottlesJugs/PlasticMilkJuiceJug/index.htm',hasChild:false},
{label:"Jugs of Juice",value:'FoodPackaging/BottlesJugs/PlasticMilkJuiceJug/index.htm',hasChild:false},
{label:"Jugs of Milk",value:'FoodPackaging/BottlesJugs/PlasticMilkJuiceJug/index.htm',hasChild:false},
{label:"Milk Bottles",value:'FoodPackaging/BottlesJugs/PlasticMilkJuiceJug/index.htm',hasChild:false},
{label:"Juice Bottles",value:'FoodPackaging/BottlesJugs/PlasticMilkJuiceJug/index.htm',hasChild:false},
{label:"Carton With Plastic Spout",value:'FoodPackaging/BoxesCartonsLiners/AsepticTetraPak/index.htm',hasChild:false},
{label:"Carton With Plastic Top",value:'FoodPackaging/BoxesCartonsLiners/AsepticTetraPak/index.htm',hasChild:false},
{label:"Tetra Pak",value:'FoodPackaging/BoxesCartonsLiners/AsepticTetraPak/index.htm',hasChild:false},
{label:"Carton With Spout",value:'FoodPackaging/BoxesCartonsLiners/AsepticTetraPak/index.htm',hasChild:false},
{label:"Soup Cartons",value:'FoodPackaging/BoxesCartonsLiners/AsepticTetraPak/index.htm',hasChild:false},
{label:"Milk Cartons",value:'FoodPackaging/BoxesCartonsLiners/AsepticTetraPak/index.htm',hasChild:false},
{label:"Juice Cartons",value:'FoodPackaging/BoxesCartonsLiners/AsepticTetraPak/index.htm',hasChild:false},
{label:"Margarine Boxes",value:'FoodPackaging/BoxesCartonsLiners/ButterBoxes/index.htm',hasChild:false},
{label:"Cracker Boxes",value:'FoodPackaging/BoxesCartonsLiners/CerealCrackerBoxes/index.htm',hasChild:false},
{label:"Snack Boxes",value:'FoodPackaging/BoxesCartonsLiners/CerealCrackerBoxes/index.htm',hasChild:false},
{label:"Egg Cartons - Paper",value:'FoodPackaging/BoxesCartonsLiners/PaperEggCartons/index.htm',hasChild:false},
{label:"Cartons - Eggs",value:'FoodPackaging/BoxesCartonsLiners/PaperEggCartons/index.htm',hasChild:false},
{label:"Box for Frozen Food",value:'FoodPackaging/BoxesCartonsLiners/FrozenFoodBoxes/index.htm',hasChild:false},
{label:"TV Dinner Boxes",value:'FoodPackaging/BoxesCartonsLiners/FrozenFoodBoxes/index.htm',hasChild:false},
{label:"Frozen Dinner Boxes",value:'FoodPackaging/BoxesCartonsLiners/FrozenFoodBoxes/index.htm',hasChild:false},
{label:"Ice Cream Boxes",value:'FoodPackaging/BoxesCartonsLiners/IceCreamCartons/index.htm',hasChild:false},
{label:"Ice Cream Containers",value:'FoodPackaging/BoxesCartonsLiners/IceCreamCartons/index.htm',hasChild:false},
{label:"Sippy Boxes",value:'FoodPackaging/BoxesCartonsLiners/JuiceBoxes/index.htm',hasChild:false},
{label:"Juice Containers",value:'FoodPackaging/BoxesCartonsLiners/JuiceBoxes/index.htm',hasChild:false},
{label:"Mixed Metal and Cardboard",value:'FoodPackaging/BoxesCartonsLiners/CardboardMetalContainers/index.htm',hasChild:false},
{label:"Mixed Metal Containers",value:'FoodPackaging/BoxesCartonsLiners/CardboardMetalContainers/index.htm',hasChild:false},
{label:"Nut Containers",value:'FoodPackaging/BoxesCartonsLiners/CardboardMetalContainers/index.htm',hasChild:false},
{label:"Nut Canisters",value:'FoodPackaging/BoxesCartonsLiners/CardboardMetalContainers/index.htm',hasChild:false},
{label:"Potato Chip Canisters",value:'FoodPackaging/BoxesCartonsLiners/CardboardMetalContainers/index.htm',hasChild:false},
{label:"Potato Chip Containers",value:'FoodPackaging/BoxesCartonsLiners/CardboardMetalContainers/index.htm',hasChild:false},
{label:"Coffee Canisters",value:'FoodPackaging/BoxesCartonsLiners/CardboardMetalContainers/index.htm',hasChild:false},
{label:"Coffee Containers",value:'FoodPackaging/BoxesCartonsLiners/CardboardMetalContainers/index.htm',hasChild:false},
{label:"Berry Baskets - Paper",value:'FoodPackaging/BoxesCartonsLiners/PaperBerryBaskets/index.htm',hasChild:false},
{label:"Fruit Baskets - Paper",value:'FoodPackaging/BoxesCartonsLiners/PaperBerryBaskets/index.htm',hasChild:false},
{label:"Strawberry Baskets - Paper",value:'FoodPackaging/BoxesCartonsLiners/PaperBerryBaskets/index.htm',hasChild:false},
{label:"Blueberry Baskets - Paper",value:'FoodPackaging/BoxesCartonsLiners/PaperBerryBaskets/index.htm',hasChild:false},
{label:"Blackberry Baskets - Paper",value:'FoodPackaging/BoxesCartonsLiners/PaperBerryBaskets/index.htm',hasChild:false},
{label:"Raspberry Baskets - Paper",value:'FoodPackaging/BoxesCartonsLiners/PaperBerryBaskets/index.htm',hasChild:false},
{label:"Soup Containers",value:'FoodPackaging/BoxesCartonsLiners/SoupBoxes/index.htm',hasChild:false},
{label:"Food Cartons",value:'FoodPackaging/BoxesCartonsLiners/Take-OutContainers/index.htm',hasChild:false},
{label:"Take Out Boxes",value:'FoodPackaging/BoxesCartonsLiners/Take-OutContainers/index.htm',hasChild:false},
{label:"To Go Boxes",value:'FoodPackaging/BoxesCartonsLiners/Take-OutContainers/index.htm',hasChild:false},
{label:"To Go Containers",value:'FoodPackaging/BoxesCartonsLiners/Take-OutContainers/index.htm',hasChild:false},
{label:"To-Go Boxes",value:'FoodPackaging/BoxesCartonsLiners/Take-OutContainers/index.htm',hasChild:false},
{label:"To-Go Containers",value:'FoodPackaging/BoxesCartonsLiners/Take-OutContainers/index.htm',hasChild:false},
{label:"Take-Out Boxes",value:'FoodPackaging/BoxesCartonsLiners/Take-OutContainers/index.htm',hasChild:false},
{label:"Filters - Coffee",value:'FoodPackaging/CoffeeFilters/index.htm',hasChild:false},
{label:"Used Coffee Filters",value:'FoodPackaging/CoffeeFilters/index.htm',hasChild:false},
{label:"Compostable Forks",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Compostable Knifes",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Compostable Plates",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Compostable Spoons",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Compostable Sporks",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Compostable Trays",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Compostable Cups",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Compostable to Go Containers",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Compostable Straws",value:'FoodPackaging/CompostableFoodServiceItems/index.htm',hasChild:false},
{label:"Wine Stoppers",value:'FoodPackaging/Corks/index.htm',hasChild:false},
{label:"Wine Corks",value:'FoodPackaging/Corks/index.htm',hasChild:false},
{label:"Beer Bottles",value:'FoodPackaging/GlassBottlesJars/index.htm',hasChild:false},
{label:"Bottles - Glass",value:'FoodPackaging/GlassBottlesJars/index.htm',hasChild:false},
{label:"Glass Bottles",value:'FoodPackaging/GlassBottlesJars/index.htm',hasChild:false},
{label:"Glass Jars",value:'FoodPackaging/GlassBottlesJars/index.htm',hasChild:false},
{label:"Glass Shards",value:'FoodPackaging/GlassBottlesJars/index.htm',hasChild:false},
{label:"Jam Jars",value:'FoodPackaging/GlassBottlesJars/index.htm',hasChild:false},
{label:"Jars - Glass",value:'FoodPackaging/GlassBottlesJars/index.htm',hasChild:false},
{label:"Food Jars",value:'FoodPackaging/GlassBottlesJars/index.htm',hasChild:false},
{label:"Starbucks Cups",value:'FoodPackaging/HotCoffeeCups/index.htm',hasChild:false},
{label:"Coffee Cups ",value:'FoodPackaging/HotCoffeeCups/index.htm',hasChild:false},
{label:"To Go Coffee Cups",value:'FoodPackaging/HotCoffeeCups/index.htm',hasChild:false},
{label:"Hot Drink Cups",value:'FoodPackaging/HotCoffeeCups/index.htm',hasChild:false},
{label:"Soup Can Lids",value:'FoodPackaging/Lids/CanLids/index.htm',hasChild:false},
{label:"Coffee Cup Lids",value:'FoodPackaging/Lids/LidsDeliCoffeeSoftDrink/index.htm',hasChild:false},
{label:"Coffee Lids",value:'FoodPackaging/Lids/LidsDeliCoffeeSoftDrink/index.htm',hasChild:false},
{label:"Deli Lids",value:'FoodPackaging/Lids/LidsDeliCoffeeSoftDrink/index.htm',hasChild:false},
{label:"Soda Lids",value:'FoodPackaging/Lids/LidsDeliCoffeeSoftDrink/index.htm',hasChild:false},
{label:"Soft Drink Cup Lids",value:'FoodPackaging/Lids/LidsDeliCoffeeSoftDrink/index.htm',hasChild:false},
{label:"Pressurized Cans",value:'FoodPackaging/MetalCansMetalLids/AerosolCans/index.htm',hasChild:false},
{label:"Spray Cans",value:'FoodPackaging/MetalCansMetalLids/AerosolCans/index.htm',hasChild:false},
{label:"Cans - Aerosol",value:'FoodPackaging/MetalCansMetalLids/AerosolCans/index.htm',hasChild:false},
{label:"Spray Paint Cans",value:'FoodPackaging/MetalCansMetalLids/AerosolCans/index.htm',hasChild:false},
{label:"Aluminum Cans",value:'FoodPackaging/MetalCansMetalLids/BeverageCans/index.htm',hasChild:false},
{label:"Beer Cans",value:'FoodPackaging/MetalCansMetalLids/BeverageCans/index.htm',hasChild:false},
{label:"Cans - Beverage",value:'FoodPackaging/MetalCansMetalLids/BeverageCans/index.htm',hasChild:false},
{label:"Pop Cans",value:'FoodPackaging/MetalCansMetalLids/BeverageCans/index.htm',hasChild:false},
{label:"Soda Cans",value:'FoodPackaging/MetalCansMetalLids/BeverageCans/index.htm',hasChild:false},
{label:"Soda Pop Cans",value:'FoodPackaging/MetalCansMetalLids/BeverageCans/index.htm',hasChild:false},
{label:"Food Cans",value:'FoodPackaging/MetalCansMetalLids/SteelTinCansLids/index.htm',hasChild:false},
{label:"Canned Food",value:'FoodPackaging/MetalCansMetalLids/SteelTinCansLids/index.htm',hasChild:false},
{label:"Boxes - Cardboard",value:'FoodPackaging/PaperCardboard/CardboardBoxes/index.htm',hasChild:false},
{label:"Moving Boxes",value:'FoodPackaging/PaperCardboard/CardboardBoxes/index.htm',hasChild:false},
{label:"Packing Boxes",value:'FoodPackaging/PaperCardboard/CardboardBoxes/index.htm',hasChild:false},
{label:"Dirty Cardboard",value:'FoodPackaging/PaperCardboard/CardboardSoiledorGreasy/index.htm',hasChild:false},
{label:"Greasy Cardboard",value:'FoodPackaging/PaperCardboard/CardboardSoiledorGreasy/index.htm',hasChild:false},
{label:"Wet Cardboard",value:'FoodPackaging/PaperCardboard/CardboardSoiledorGreasy/index.htm',hasChild:false},
{label:"Solied Cardboard",value:'FoodPackaging/PaperCardboard/CardboardSoiledorGreasy/index.htm',hasChild:false},
{label:"Disposable Cups",value:'FoodPackaging/PaperCardboard/PaperCupsCoffeeeCups/index.htm',hasChild:false},
{label:"Disposable Plates",value:'FoodPackaging/PaperCardboard/PaperCupsCoffeeeCups/index.htm',hasChild:false},
{label:"Dixie Cups",value:'FoodPackaging/PaperCardboard/PaperCupsCoffeeeCups/index.htm',hasChild:false},
{label:"Plastic Trays",value:'FoodPackaging/PlasticStyrofoamContainers/BerryTrays/index.htm',hasChild:false},
{label:"To Go Containers - Clamshell",value:'FoodPackaging/PlasticStyrofoamContainers/ClamshellContainers/index.htm',hasChild:false},
{label:"Egg Cartons - Foam",value:'Plastic/Styrofoam/FoamEggCartons/index.htm',hasChild:false},
{label:"Food Trays",value:'FoodPackaging/PlasticStyrofoamContainers/MeatFoodTrays/index.htm',hasChild:false},
{label:"Foam Trays",value:'FoodPackaging/PlasticStyrofoamContainers/MeatFoodTrays/index.htm',hasChild:false},
{label:"Beer Pong Cups",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Cups - Plastic",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Plastic Forks",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Plastic Knives",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Plastic Plates",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Plastic Serviceware",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Sporks",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Plastic Spoons",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Plastic Sporks",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Party Cups",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Red Party Cups",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Solo Cups",value:'FoodPackaging/PlasticStyrofoamContainers/PlasticCupsUtensils/index.htm',hasChild:false},
{label:"Mayonnaise Jars",value:'FoodPackaging/PlasticStyrofoamContainers/PeanutButterMayonnaiseJars/index.htm',hasChild:false},
{label:"Plastic Jars",value:'FoodPackaging/PlasticStyrofoamContainers/PeanutButterMayonnaiseJars/index.htm',hasChild:false},
{label:"Peanut Butter Jars",value:'FoodPackaging/PlasticStyrofoamContainers/PeanutButterMayonnaiseJars/index.htm',hasChild:false},
{label:"Plastic Food Jars",value:'FoodPackaging/PlasticStyrofoamContainers/PeanutButterMayonnaiseJars/index.htm',hasChild:false},
{label:"Car Glass",value:'VehiclesVehicle-related/AutoGlass/index.htm',hasChild:false},
{label:"Car Window Glass",value:'VehiclesVehicle-related/AutoGlass/index.htm',hasChild:false},
{label:"Windshield Glass",value:'VehiclesVehicle-related/AutoGlass/index.htm',hasChild:false},
{label:"Chalices",value:'GlassCeramics/DrinkingGlasses/index.htm',hasChild:false},
{label:"Drink Glasses",value:'GlassCeramics/DrinkingGlasses/index.htm',hasChild:false},
{label:"Tumblers",value:'GlassCeramics/DrinkingGlasses/index.htm',hasChild:false},
{label:"Glasses",value:'GlassCeramics/EyeGlasses/index.htm',hasChild:false},
{label:"Ceramic Household Items",value:'GlassCeramics/GlassCeramicHouseholdItems/index.htm',hasChild:false},
{label:"Ceramics",value:'GlassCeramics/GlassCeramicHouseholdItems/index.htm',hasChild:false},
{label:"Plates - Ceramic",value:'GlassCeramics/GlassCeramicHouseholdItems/index.htm',hasChild:false},
{label:"Bowls - Ceramic",value:'GlassCeramics/GlassCeramicHouseholdItems/index.htm',hasChild:false},
{label:"Glass - Vase",value:'GlassCeramics/GlassCeramicHouseholdItems/index.htm',hasChild:false},
{label:"Ammo",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Assault Rifles",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Bullets",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Shell Casings",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Casings",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Firearms",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Guns",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Handguns",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Munitions",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Pistols",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Revolvers",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Rifles",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Shells",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Shotguns",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Shotgun Shells",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Pellet Guns",value:'HazardousItems/AmmunitionGuns/index.htm',hasChild:false},
{label:"Acetylene Tanks",value:'HazardousItems/CompressedGasContainers/OxygenAcetyleneTanks/index.htm',hasChild:false},
{label:"Welding Gas Tanks",value:'HazardousItems/CompressedGasContainers/OxygenAcetyleneTanks/index.htm',hasChild:false},
{label:"Oxy Acetylene Tanks",value:'HazardousItems/CompressedGasContainers/OxygenAcetyleneTanks/index.htm',hasChild:false},
{label:"Oxy-Acetylene Tanks",value:'HazardousItems/CompressedGasContainers/OxygenAcetyleneTanks/index.htm',hasChild:false},
{label:"Gas Tanks - Welding",value:'HazardousItems/CompressedGasContainers/OxygenAcetyleneTanks/index.htm',hasChild:false},
{label:"Barbeque Tanks",value:'HazardousItems/CompressedGasContainers/PropaneTanks/index.htm',hasChild:false},
{label:"BBQ Tanks",value:'HazardousItems/CompressedGasContainers/PropaneTanks/index.htm',hasChild:false},
{label:"Small Gas Cans",value:'HazardousItems/CompressedGasContainers/GasCanistersSmall/index.htm',hasChild:false},
{label:"Coleman Gas Cans",value:'HazardousItems/CompressedGasContainers/GasCanistersSmall/index.htm',hasChild:false},
{label:"Camping Gas Cans",value:'HazardousItems/CompressedGasContainers/GasCanistersSmall/index.htm',hasChild:false},
{label:"Camping Stove Gas Cans",value:'HazardousItems/CompressedGasContainers/GasCanistersSmall/index.htm',hasChild:false},
{label:"Firecrackers",value:'HazardousItems/Fireworks/index.htm',hasChild:false},
{label:"Mortars",value:'HazardousItems/Fireworks/index.htm',hasChild:false},
{label:"Bottle Rockets",value:'HazardousItems/Fireworks/index.htm',hasChild:false},
{label:"Transmission Fluid ",value:'VehiclesVehicle-related/BrakeTransmissionFluid/index.htm',hasChild:false},
{label:"Hydraulic Fluid",value:'VehiclesVehicle-related/BrakeTransmissionFluid/index.htm',hasChild:false},
{label:"Detergents",value:'HazardousItems/LiquidsHouseholdSupplies/CleaningSupplies/index.htm',hasChild:false},
{label:"Janitorial Supplies",value:'HazardousItems/LiquidsHouseholdSupplies/CleaningSupplies/index.htm',hasChild:false},
{label:"Toilet Cleaner",value:'HazardousItems/LiquidsHouseholdSupplies/CleaningSupplies/index.htm',hasChild:false},
{label:"Window Cleaner",value:'HazardousItems/LiquidsHouseholdSupplies/CleaningSupplies/index.htm',hasChild:false},
{label:"Household Chemicals",value:'HazardousItems/LiquidsHouseholdSupplies/CleaningSupplies/index.htm',hasChild:false},
{label:"Gas",value:'HazardousItems/LiquidsHouseholdSupplies/Gasoline/index.htm',hasChild:false},
{label:"Adhesives",value:'HazardousItems/LiquidsHouseholdSupplies/GluesAdhesives/index.htm',hasChild:false},
{label:"Elmers Glue",value:'HazardousItems/LiquidsHouseholdSupplies/GluesAdhesives/index.htm',hasChild:false},
{label:"Glue Sticks",value:'HazardousItems/LiquidsHouseholdSupplies/GluesAdhesives/index.htm',hasChild:false},
{label:"Paste",value:'HazardousItems/LiquidsHouseholdSupplies/GluesAdhesives/index.htm',hasChild:false},
{label:"Super Glue",value:'HazardousItems/LiquidsHouseholdSupplies/GluesAdhesives/index.htm',hasChild:false},
{label:"Wood Glue",value:'HazardousItems/LiquidsHouseholdSupplies/GluesAdhesives/index.htm',hasChild:false},
{label:"Craft Chemicals",value:'HazardousItems/LiquidsHouseholdSupplies/HobbyChemicals/index.htm',hasChild:false},
{label:"Auto Oil",value:'HazardousItems/LiquidsHouseholdSupplies/MotorOil/index.htm',hasChild:false},
{label:"Automobile Oil",value:'HazardousItems/LiquidsHouseholdSupplies/MotorOil/index.htm',hasChild:false},
{label:"Synthetic Motor Oil",value:'HazardousItems/LiquidsHouseholdSupplies/MotorOil/index.htm',hasChild:false},
{label:"Engine Oil",value:'HazardousItems/LiquidsHouseholdSupplies/MotorOil/index.htm',hasChild:false},
{label:"Car Oil ",value:'HazardousItems/LiquidsHouseholdSupplies/MotorOil/index.htm',hasChild:false},
{label:"Chlorine",value:'HazardousItems/LiquidsHouseholdSupplies/PoolSpaChemicals/index.htm',hasChild:false},
{label:"Spa Chemicals",value:'HazardousItems/LiquidsHouseholdSupplies/PoolSpaChemicals/index.htm',hasChild:false},
{label:"Bromine",value:'HazardousItems/LiquidsHouseholdSupplies/PoolSpaChemicals/index.htm',hasChild:false},
{label:"Hazardous Chemicals",value:'HazardousItems/LiquidsHouseholdSupplies/Solvents/index.htm',hasChild:false},
{label:"Over the Counter Medicines",value:'HazardousItems/Medicine/index.htm',hasChild:false},
{label:"Prescription Medicine",value:'HazardousItems/Medicine/index.htm',hasChild:false},
{label:"Prescriptions",value:'HazardousItems/Medicine/index.htm',hasChild:false},
{label:"Medication",value:'HazardousItems/Medicine/index.htm',hasChild:false},
{label:"Mercury",value:'HazardousItems/MercuryThermometersItems/index.htm',hasChild:false},
{label:"Heroin Needles",value:'HazardousItems/NeedlesSyringes/index.htm',hasChild:false},
{label:"Insulin Needles",value:'HazardousItems/NeedlesSyringes/index.htm',hasChild:false},
{label:"Needles",value:'HazardousItems/NeedlesSyringes/index.htm',hasChild:false},
{label:"Sharps",value:'HazardousItems/NeedlesSyringes/index.htm',hasChild:false},
{label:"Syringes",value:'HazardousItems/NeedlesSyringes/index.htm',hasChild:false},
{label:"Weed Killer",value:'HazardousItems/Pesticides/index.htm',hasChild:false},
{label:"Weed and Feed",value:'HazardousItems/Pesticides/index.htm',hasChild:false},
{label:"Herbicides",value:'HazardousItems/Pesticides/index.htm',hasChild:false},
{label:"Fungicides",value:'HazardousItems/Pesticides/index.htm',hasChild:false},
{label:"Insecticides",value:'HazardousItems/Pesticides/index.htm',hasChild:false},
{label:"Bug Killer",value:'HazardousItems/Pesticides/index.htm',hasChild:false},
{label:"Drums ",value:'MetalandMetalItems/BarrelsDrums/index.htm',hasChild:false},
{label:"Oil Barrels",value:'MetalandMetalItems/BarrelsDrums/index.htm',hasChild:false},
{label:"Oil Drums",value:'MetalandMetalItems/BarrelsDrums/index.htm',hasChild:false},
{label:"Steel Drums",value:'MetalandMetalItems/BarrelsDrums/index.htm',hasChild:false},
{label:"Pie Tins",value:'MetalandMetalItems/FromtheKitchen/FoilPiePans/index.htm',hasChild:false},
{label:"Pie Plates",value:'MetalandMetalItems/FromtheKitchen/FoilPiePans/index.htm',hasChild:false},
{label:"Lids - Jar",value:'MetalandMetalItems/FromtheKitchen/JarLids/index.htm',hasChild:false},
{label:"Jam Jar Lids",value:'MetalandMetalItems/FromtheKitchen/JarLids/index.htm',hasChild:false},
{label:"Cast Iron Skillets",value:'MetalandMetalItems/FromtheKitchen/PotsPans/index.htm',hasChild:false},
{label:"Cooking Pots",value:'MetalandMetalItems/FromtheKitchen/PotsPans/index.htm',hasChild:false},
{label:"Frying Pans",value:'MetalandMetalItems/FromtheKitchen/PotsPans/index.htm',hasChild:false},
{label:"Pans",value:'MetalandMetalItems/FromtheKitchen/PotsPans/index.htm',hasChild:false},
{label:"Pie Pans ",value:'MetalandMetalItems/FromtheKitchen/PotsPans/index.htm',hasChild:false},
{label:"Saucepans",value:'MetalandMetalItems/FromtheKitchen/PotsPans/index.htm',hasChild:false},
{label:"Skillets",value:'MetalandMetalItems/FromtheKitchen/PotsPans/index.htm',hasChild:false},
{label:"Wok",value:'MetalandMetalItems/FromtheKitchen/PotsPans/index.htm',hasChild:false},
{label:"Forks",value:'MetalandMetalItems/FromtheKitchen/Silverware/index.htm',hasChild:false},
{label:"Knives",value:'MetalandMetalItems/FromtheKitchen/Silverware/index.htm',hasChild:false},
{label:"Serviceware",value:'MetalandMetalItems/FromtheKitchen/Silverware/index.htm',hasChild:false},
{label:"Spoons",value:'MetalandMetalItems/FromtheKitchen/Silverware/index.htm',hasChild:false},
{label:"Kitchen Tools",value:'MetalandMetalItems/FromtheKitchen/Silverware/index.htm',hasChild:false},
{label:"Fans",value:'MetalandMetalItems/FromtheKitchen/SmallAppliances/index.htm',hasChild:false},
{label:"Kitchen Gadgets",value:'MetalandMetalItems/FromtheKitchen/SmallAppliances/index.htm',hasChild:false},
{label:"Household Applicances",value:'MetalandMetalItems/FromtheKitchen/SmallAppliances/index.htm',hasChild:false},
{label:"Coffee Grinder",value:'MetalandMetalItems/FromtheKitchen/SmallAppliances/index.htm',hasChild:false},
{label:"Wine Foils",value:'MetalandMetalItems/FromtheKitchen/WineBottleFoil/index.htm',hasChild:false},
{label:"Foil - Aluminum",value:'MetalandMetalItems/FromtheKitchen/AluminumFoil/index.htm',hasChild:false},
{label:"Awls",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Claw Hammer",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Hammers",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Needle Nose Pliers",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Tape Measure",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Chisel",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Level",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Pliers",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Roofing Hammer",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Screw Drivers",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Wrenches",value:'MetalandMetalItems/HandTools/index.htm',hasChild:false},
{label:"Coins",value:'MetalandMetalItems/JewelryCoins/index.htm',hasChild:false},
{label:"Necklaces",value:'MetalandMetalItems/JewelryCoins/index.htm',hasChild:false},
{label:"Pendants",value:'MetalandMetalItems/JewelryCoins/index.htm',hasChild:false},
{label:"Bracelets",value:'MetalandMetalItems/JewelryCoins/index.htm',hasChild:false},
{label:"Rings",value:'MetalandMetalItems/JewelryCoins/index.htm',hasChild:false},
{label:"Earrings",value:'MetalandMetalItems/JewelryCoins/index.htm',hasChild:false},
{label:"Aluminum Pans",value:'MetalandMetalItems/MetalsbyType/Aluminum/index.htm',hasChild:false},
{label:"Aluminum Scrap",value:'MetalandMetalItems/MetalsbyType/Aluminum/index.htm',hasChild:false},
{label:"Pipe",value:'MetalandMetalItems/MetalsbyType/CastIron/index.htm',hasChild:false},
{label:"Brass",value:'MetalandMetalItems/MetalsbyType/CopperBronzeBrass/index.htm',hasChild:false},
{label:"Bronze",value:'MetalandMetalItems/MetalsbyType/CopperBronzeBrass/index.htm',hasChild:false},
{label:"Precious Metals",value:'MetalandMetalItems/MetalsbyType/GoldSilverEtc/index.htm',hasChild:false},
{label:"Silver",value:'MetalandMetalItems/MetalsbyType/GoldSilverEtc/index.htm',hasChild:false},
{label:"Steel",value:'MetalandMetalItems/MetalsbyType/IronSteel/index.htm',hasChild:false},
{label:"Ferrous Metal",value:'MetalandMetalItems/MetalsbyType/ScrapMetal/index.htm',hasChild:false},
{label:"Hangers",value:'MetalandMetalItems/MetalsbyType/ScrapMetal/index.htm',hasChild:false},
{label:"Metal",value:'MetalandMetalItems/MetalsbyType/ScrapMetal/index.htm',hasChild:false},
{label:"Metal Bits",value:'MetalandMetalItems/MetalsbyType/ScrapMetal/index.htm',hasChild:false},
{label:"Metal Food Trays",value:'MetalandMetalItems/MetalsbyType/ScrapMetal/index.htm',hasChild:false},
{label:"Metal Pieces",value:'MetalandMetalItems/MetalsbyType/ScrapMetal/index.htm',hasChild:false},
{label:"Metal Scraps",value:'MetalandMetalItems/MetalsbyType/ScrapMetal/index.htm',hasChild:false},
{label:"Tin",value:'MetalandMetalItems/MetalsbyType/ScrapMetal/index.htm',hasChild:false},
{label:"Ring of Keys",value:'MetalandMetalItems/SmallMetalItems/Keys/index.htm',hasChild:false},
{label:"Bolts",value:'MetalandMetalItems/SmallMetalItems/ScrewsNailsNutsBolts/index.htm',hasChild:false},
{label:"Hardware",value:'MetalandMetalItems/SmallMetalItems/ScrewsNailsNutsBolts/index.htm',hasChild:false},
{label:"Metal Washers",value:'MetalandMetalItems/SmallMetalItems/ScrewsNailsNutsBolts/index.htm',hasChild:false},
{label:"Nails",value:'MetalandMetalItems/SmallMetalItems/ScrewsNailsNutsBolts/index.htm',hasChild:false},
{label:"Washers - Metal",value:'MetalandMetalItems/SmallMetalItems/ScrewsNailsNutsBolts/index.htm',hasChild:false},
{label:"Nuts",value:'MetalandMetalItems/SmallMetalItems/ScrewsNailsNutsBolts/index.htm',hasChild:false},
{label:"Cable",value:'MetalandMetalItems/WireCable/index.htm',hasChild:false},
{label:"Foamboard",value:'Paper/Cardboard/Foamcore/index.htm',hasChild:false},
{label:"Cartons of Juice",value:'Paper/ContainersBoxesCartons/MilkJuiceCartons/index.htm',hasChild:false},
{label:"Soup Cartons",value:'Paper/ContainersBoxesCartons/MilkJuiceCartons/index.htm',hasChild:false},
{label:"Juice Cartons",value:'Paper/ContainersBoxesCartons/MilkJuiceCartons/index.htm',hasChild:false},
{label:"Detergent Boxes",value:'Paper/ContainersBoxesCartons/LaundryDetergentBoxes/index.htm',hasChild:false},
{label:"Laundry Soap Box",value:'Paper/ContainersBoxesCartons/LaundryDetergentBoxes/index.htm',hasChild:false},
{label:"Cups - Paper",value:'Paper/ContainersBoxesCartons/PaperCupsCoffeeCups/index.htm',hasChild:false},
{label:"Kleenex - Box",value:'Paper/ContainersBoxesCartons/TissueBoxes/index.htm',hasChild:false},
{label:"Food Wrapper - Paper",value:'Paper/Food-soiledPaper/index.htm',hasChild:false},
{label:"Kleenexes",value:'Paper/Misc.Paper/FacialTissue/index.htm',hasChild:false},
{label:"Tissues",value:'Paper/Misc.Paper/FacialTissue/index.htm',hasChild:false},
{label:"Used Kleenexes",value:'Paper/Misc.Paper/FacialTissue/index.htm',hasChild:false},
{label:"Used Tissues",value:'Paper/Misc.Paper/FacialTissue/index.htm',hasChild:false},
{label:"Christmas Paper",value:'Paper/Misc.Paper/GiftWrap/index.htm',hasChild:false},
{label:"Wrapping Paper",value:'Paper/Misc.Paper/GiftWrap/index.htm',hasChild:false},
{label:"Dirty Napkins",value:'Paper/Misc.Paper/Napkins/index.htm',hasChild:false},
{label:"Used Napkins",value:'Paper/Misc.Paper/Napkins/index.htm',hasChild:false},
{label:"Soiled Napkins",value:'Paper/Misc.Paper/Napkins/index.htm',hasChild:false},
{label:"5 Star Notebooks ",value:'Paper/PaperPrintedReading/Notebooks-Spiralbound/index.htm',hasChild:false},
{label:"Steno Pads",value:'Paper/PaperPrintedReading/Notebooks-Spiralbound/index.htm',hasChild:false},
{label:"Notepad",value:'Paper/PaperPrintedReading/Notebooks-Spiralbound/index.htm',hasChild:false},
{label:"Paper Grocery Bags",value:'Paper/Misc.Paper/PaperBags/index.htm',hasChild:false},
{label:"Grocery Bags - Paper",value:'Paper/Misc.Paper/PaperBags/index.htm',hasChild:false},
{label:"Used Paper Towels",value:'Paper/Misc.Paper/PaperTowels/index.htm',hasChild:false},
{label:"Paper Shredded",value:'Paper/Misc.Paper/ShreddedPaper/index.htm',hasChild:false},
{label:"Hardcover Books ",value:'Paper/PaperPrintedReading/BooksHardback/index.htm',hasChild:false},
{label:"Textbooks - Hardback",value:'Paper/PaperPrintedReading/BooksHardback/index.htm',hasChild:false},
{label:"Textbooks - Paperback",value:'Paper/PaperPrintedReading/BooksPaperback/index.htm',hasChild:false},
{label:"Softcover Books",value:'Paper/PaperPrintedReading/BooksPaperback/index.htm',hasChild:false},
{label:"Envelopes - Plastic",value:'Paper/PaperPrintedReading/EnvelopesTyvek/index.htm',hasChild:false},
{label:"Birthday Cards",value:'Paper/PaperPrintedReading/GreetingCards/index.htm',hasChild:false},
{label:"Cards",value:'Paper/PaperPrintedReading/GreetingCards/index.htm',hasChild:false},
{label:"Holiday Cards",value:'Paper/PaperPrintedReading/GreetingCards/index.htm',hasChild:false},
{label:"Coupons",value:'Paper/PaperPrintedReading/JunkMail/index.htm',hasChild:false},
{label:"Catalogues",value:'Paper/PaperPrintedReading/Magazines/index.htm',hasChild:false},
{label:"Computer Papers",value:'Paper/PaperPrintedReading/OfficePaper/index.htm',hasChild:false},
{label:"Heat Printed Paper",value:'Paper/PaperPrintedReading/OfficePaper/index.htm',hasChild:false},
{label:"Hole Punch Paper",value:'Paper/PaperPrintedReading/OfficePaper/index.htm',hasChild:false},
{label:"Paper",value:'Paper/PaperPrintedReading/OfficePaper/index.htm',hasChild:false},
{label:"White Papers",value:'Paper/PaperPrintedReading/OfficePaper/index.htm',hasChild:false},
{label:"White Pages",value:'Paper/PaperPrintedReading/PhoneBooks/index.htm',hasChild:false},
{label:"Yellow Pages",value:'Paper/PaperPrintedReading/PhoneBooks/index.htm',hasChild:false},
{label:"Photo Paper",value:'Paper/PaperPrintedReading/Photographs/index.htm',hasChild:false},
{label:"Pictures",value:'Paper/PaperPrintedReading/Photographs/index.htm',hasChild:false},
{label:"Plastic Suit Bag",value:'Plastic/Bags/DryCleanerBags/index.htm',hasChild:false},
{label:"#1 Plastic",value:'Plastic/WithRecycleNumbers/index.htm',hasChild:false},
{label:"#2 Plastic",value:'Plastic/WithRecycleNumbers/index.htm',hasChild:false},
{label:"#3 Plastic",value:'Plastic/WithRecycleNumbers/index.htm',hasChild:false},
{label:"#4 Plastic",value:'Plastic/WithRecycleNumbers/index.htm',hasChild:false},
{label:"#5 Plastic",value:'Plastic/WithRecycleNumbers/index.htm',hasChild:false},
{label:"#6 Plastic",value:'Plastic/WithRecycleNumbers/index.htm',hasChild:false},
{label:"#7 Plastic",value:'Plastic/WithRecycleNumbers/index.htm',hasChild:false},
{label:"Six Pack Rings",value:'Plastic/FoodBeverageContainers/6-packPlasticRings/index.htm',hasChild:false},
{label:"Hard Plastic Packaging",value:'Plastic/FoodBeverageContainers/BlisterPackages/index.htm',hasChild:false},
{label:"Molded Plastic Packaging",value:'Plastic/FoodBeverageContainers/BlisterPackages/index.htm',hasChild:false},
{label:"Rigid Plastic Packaging",value:'Plastic/FoodBeverageContainers/BlisterPackages/index.htm',hasChild:false},
{label:"Toy Plastic Packaging",value:'Plastic/FoodBeverageContainers/BlisterPackages/index.htm',hasChild:false},
{label:"Foam Boards",value:'Plastic/Styrofoam/FoamPackingSheets/index.htm',hasChild:false},
{label:"Foam Packaging",value:'Plastic/Styrofoam/FoamPackingSheets/index.htm',hasChild:false},
{label:"Package Foam",value:'Plastic/Styrofoam/FoamPackingSheets/index.htm',hasChild:false},
{label:"Packing Foam",value:'Plastic/Styrofoam/FoamPackingSheets/index.htm',hasChild:false},
{label:"Foam Core",value:'Plastic/Styrofoam/FoamPackingSheets/index.htm',hasChild:false},
{label:"Corn Starch Peanuts",value:'Plastic/MailPackaging/PackingPeanuts/index.htm',hasChild:false},
{label:"Styrofoam Peanuts",value:'Plastic/MailPackaging/PackingPeanuts/index.htm',hasChild:false},
{label:"Biodegradable Foam Peanuts",value:'Plastic/MailPackaging/PackingPeanuts/index.htm',hasChild:false},
{label:"Bottle Tops",value:'Plastic/Misc.Plastic/BottleCaps/index.htm',hasChild:false},
{label:"Beer Caps",value:'Plastic/Misc.Plastic/BottleCaps/index.htm',hasChild:false},
{label:"Jewel Cases",value:'Plastic/Misc.Plastic/CDCases/index.htm',hasChild:false},
{label:"DVD Cases",value:'Plastic/Misc.Plastic/CDCases/index.htm',hasChild:false},
{label:"CD Cases",value:'Plastic/Misc.Plastic/CDCases/index.htm',hasChild:false},
{label:"Glasses Frames",value:'Plastic/Misc.Plastic/EyeglassFrames/index.htm',hasChild:false},
{label:"Cartridges - Printer",value:'Plastic/Misc.Plastic/PrinterCartridges/index.htm',hasChild:false},
{label:"Dry Cleaning Bags",value:'Plastic/Misc.Plastic/ShrinkWrap/index.htm',hasChild:false},
{label:"Plastic Film",value:'Plastic/Misc.Plastic/ShrinkWrap/index.htm',hasChild:false},
{label:"Advil Bottles",value:'Plastic/Non-FoodContainers/MedicineBottles/index.htm',hasChild:false},
{label:"Aspirin Containers",value:'Plastic/Non-FoodContainers/MedicineBottles/index.htm',hasChild:false},
{label:"Iburprofen Bottles",value:'Plastic/Non-FoodContainers/MedicineBottles/index.htm',hasChild:false},
{label:"Tylenol Bottles",value:'Plastic/Non-FoodContainers/MedicineBottles/index.htm',hasChild:false},
{label:"Mop Buckets",value:'Plastic/Non-FoodContainers/Buckets/index.htm',hasChild:false},
{label:"Pails",value:'Plastic/Non-FoodContainers/Buckets/index.htm',hasChild:false},
{label:"Detergent Jugs",value:'Plastic/Non-FoodContainers/LaundryDetergentJugs/index.htm',hasChild:false},
{label:"Bug Spray Bottles",value:'',hasChild:false},
{label:"Weed Killer Bottles",value:'',hasChild:false},
{label:"Food Tubs",value:'Plastic/FoodBeverageContainers/PlasticTubs/index.htm',hasChild:false},
{label:"Yogurt Tubs",value:'Plastic/FoodBeverageContainers/PlasticTubs/index.htm',hasChild:false},
{label:"Margarine Tubs",value:'Plastic/FoodBeverageContainers/PlasticTubs/index.htm',hasChild:false},
{label:"Margarine Containers",value:'Plastic/FoodBeverageContainers/PlasticTubs/index.htm',hasChild:false},
{label:"Yogurt Containers",value:'Plastic/FoodBeverageContainers/PlasticTubs/index.htm',hasChild:false},
{label:"Plastic Tubs",value:'Plastic/FoodBeverageContainers/PlasticTubs/index.htm',hasChild:false},
{label:"Tupperware",value:'Plastic/FoodBeverageContainers/PlasticTubs/index.htm',hasChild:false},
{label:"Prescription Bottles",value:'Plastic/Non-FoodContainers/PrescriptionDrugContainers/index.htm',hasChild:false},
{label:"Pill Bottles",value:'Plastic/Non-FoodContainers/PrescriptionDrugContainers/index.htm',hasChild:false},
{label:"Rx Bottles",value:'Plastic/Non-FoodContainers/PrescriptionDrugContainers/index.htm',hasChild:false},
{label:"Conditioner Bottles",value:'Plastic/Non-FoodContainers/ShampooLotionBottles/index.htm',hasChild:false},
{label:"Lotion Bottles",value:'Plastic/Non-FoodContainers/ShampooLotionBottles/index.htm',hasChild:false},
{label:"Soap Bottles",value:'Plastic/Non-FoodContainers/ShampooLotionBottles/index.htm',hasChild:false},
{label:"Cups - Styrofoam",value:'Plastic/Styrofoam/StyrofoamCupsUtensils/index.htm',hasChild:false},
{label:"Styrofoam",value:'Plastic/Styrofoam/StyrofoamBlocks/index.htm',hasChild:false},
{label:"Styrofoam Packaging",value:'Plastic/Styrofoam/StyrofoamBlocks/index.htm',hasChild:false},
{label:"Auto Engines",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Automobile Engines",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Car Engines",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Starters",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Transmissions",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Car Motors",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Car Parts",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Carbureators",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Fuel Injectors",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Gas Tanks",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Gaskets",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Motors",value:'VehiclesVehicle-related/EnginesMotorsandCarParts/index.htm',hasChild:false},
{label:"Emergency Flares",value:'VehiclesVehicle-related/Flares/index.htm',hasChild:false},
{label:"Road Flares",value:'VehiclesVehicle-related/Flares/index.htm',hasChild:false},
{label:"Car Fluids",value:'VehiclesVehicle-related/OtherVehicleFluids/index.htm',hasChild:false},
{label:"Power Steering Fluid",value:'VehiclesVehicle-related/OtherVehicleFluids/index.htm',hasChild:false},
{label:"Windshield Washer Fluid",value:'VehiclesVehicle-related/OtherVehicleFluids/index.htm',hasChild:false},
{label:"Cars",value:'VehiclesVehicle-related/Vehicles/index.htm',hasChild:false},
{label:"SUVs",value:'VehiclesVehicle-related/Vehicles/index.htm',hasChild:false},
{label:"Trucks",value:'VehiclesVehicle-related/Vehicles/index.htm',hasChild:false},
{label:"Vehicle Batteries",value:'VehiclesVehicle-related/VehicleBatteries/index.htm',hasChild:false},
{label:"Batteries - Car",value:'VehiclesVehicle-related/VehicleBatteries/index.htm',hasChild:false},
{label:"Batteries - Vehicle",value:'VehiclesVehicle-related/VehicleBatteries/index.htm',hasChild:false},
{label:"Christmas Wreaths",value:'YardWaste/ChristmasTrees/index.htm',hasChild:false},
{label:"Xmas Trees",value:'YardWaste/ChristmasTrees/index.htm',hasChild:false},
{label:"Unpainted Boards",value:'Wood/ReusableLumber/index.htm',hasChild:false},
{label:"Untreated Boards",value:'Wood/ReusableLumber/index.htm',hasChild:false},
{label:"Untreated Wood",value:'Wood/ReusableLumber/index.htm',hasChild:false},
{label:"Unpainted Wood",value:'Wood/ReusableLumber/index.htm',hasChild:false},
{label:"Lumber",value:'Wood/ReusableLumber/index.htm',hasChild:false},
{label:"Wood Shavings",value:'Wood/WoodScrapsShavings/index.htm',hasChild:false},
{label:"Sawdust",value:'Wood/WoodScrapsShavings/index.htm',hasChild:false},
{label:"Wood Chips",value:'Wood/WoodScrapsShavings/index.htm',hasChild:false},
{label:"Sod",value:'YardWaste/GrassClipingsSod/index.htm',hasChild:false},
{label:"Potted Plants",value:'YardWaste/HousePlants/index.htm',hasChild:false},
{label:"Live Plants",value:'YardWaste/HousePlants/index.htm',hasChild:false},
{label:"Plants in Pots ",value:'YardWaste/HousePlants/index.htm',hasChild:false},
{label:"Garden Waste",value:'YardWaste/LeavesNon-WoodyYardwaste/index.htm',hasChild:false},
{label:"Compost",value:'YardWaste/LeavesNon-WoodyYardwaste/index.htm',hasChild:false},
{label:"Yard Debris",value:'YardWaste/LeavesNon-WoodyYardwaste/index.htm',hasChild:false},
{label:"Yard Waste",value:'YardWaste/LeavesNon-WoodyYardwaste/index.htm',hasChild:false},
{label:"Leaves",value:'YardWaste/LeavesNon-WoodyYardwaste/index.htm',hasChild:false},
{label:"Weeds",value:'YardWaste/LeavesNon-WoodyYardwaste/index.htm',hasChild:false}
];

export default whereDoesItGo;
